- name: Install RPM Build tool
  package:
    name:
      - rpm-build
      - copr-cli
    state: installed

- name: Install Jenkins plugins using password.
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home }}"
    params:
      url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    state: "{{ jenkins_plugins_state }}"
    timeout: "{{ jenkins_plugin_timeout }}"
    updates_expiration: "{{ jenkins_plugin_updates_expiration }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
  with_items: "{{ nightly_plugins }}"
  when: jenkins_admin_password != ""

- name: Restart jenkins
  service: name=jenkins state=restarted

- name: Wait for Jenkins to start up before proceeding.
  shell: "curl -D - --silent --max-time 5 http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli/"
  register: result
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false
  check_mode: no

- name: Ensures {{jenkins_home}}/.config dir exists
  file: path={{jenkins_home}}/.config state=directory

- name: Ensure previous version of file is removed
  file:
    state: absent
    path: "{{ jenkins_home }}/.config/copr"

- name: Setting up credentials for pki-jenkins-bot to perform daily builds.
  copy:
    src: copr.j2
    dest: "{{ jenkins_home }}/.config/copr"

- name: Copy the Jenkins Nightlies job xml
  template: src=buildJob.xml.j2 dest=/tmp/{{ jenkins_job_name }}.xml

- name: Checking available jobs
  become: true
  shell: "java -jar {{jenkins_jar_location}} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/ list-jobs --username {{jenkins_admin_username}} --password {{jenkins_admin_password}}"
  register: available_jobs
  changed_when: "available_jobs.stdout.find(jenkins_job_name) == -1"

- name: Creating Nightlies Jenkins job
  shell: "java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/ create-job {{ jenkins_job_name }} < /tmp/{{ jenkins_job_name }}.xml --username {{jenkins_admin_username}} --password {{jenkins_admin_password}}"
  when: "available_jobs.stdout.find(jenkins_job_name) == -1"

- name: Ensure previous version of the script is removed
  file:
    state: absent
    path: "{{ jenkins_home }}/scripts"

- name: Ensures {{jenkins_home}}/scripts dir exists
  file: path={{jenkins_home}}/scripts state=directory
  
- name: Copy scripts to clean old COPR builds
  copy:
    src: "{{item}}"
    dest: "{{ jenkins_home }}/scripts"
  with_items:
    - pki-copr.py
    - utils.py

- name: Changing perm of "pki-copr.py", adding "+x"
  file: dest=/{{ jenkins_home }}/scripts/pki-copr.py mode=a+x

